version: '3'

services:
  metroapartmentmap:
    image: nint8835/metroapartmentmap
    restart: always
    networks:
      - web
    volumes:
      - ./apartments.json:/usr/src/app/apartments.json
    expose:
      - 3000
    labels:
      traefik.enable: true
      traefik.frontend.rule: "Host: metroapartmentmap.rileyflynn.me"
      traefik.port: 3000
      traefik.frontend.entryPoints: "https"
  
networks:
  web:
    external: true